### PR TITLE
feat(*) Add buildParams for building querystrings.

### PR DESCRIPTION
**Pull request by yelvert**

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Can I get you to sign the CLA and update the commit message per guidelines please? The CLA is here: https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1  Guidelines are here: https://github.com/durandalproject/about/blob/master/CONTRIBUTING.md

**Comment by yelvert** [comment]
@EisenbergEffect CLA has been signed, and commit updated. Let me know if theres anything else I need to do.

**Comment by EisenbergEffect** [comment]
Super :) I'm working on http now. So, this will get incorporated soon. Probably won't be able to take the other PR, due to big overhaul in client, but this one we can take and it should be simple to incorporate it in the client.

**Comment by EisenbergEffect** [comment]
It's in! Thanks!

**Pull request closed without merging**
